
CREATE TABLE sftp_cert (sftp_cert varchar(2000));
INSERT INTO sftp_cert (sftp_cert)
   VALUES ('-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACAl8rvaN3cCVHwSCMSreMn9y9apzWChgu5pW7P7rsHOJQAAAJBQpjt5UKY7
eQAAAAtzc2gtZWQyNTUxOQAAACAl8rvaN3cCVHwSCMSreMn9y9apzWChgu5pW7P7rsHOJQ
AAAEDR52EuNcbZFqs1ohclXBvRFQCulTryAyK5ZPYd3NoDOiXyu9o3dwJUfBIIxKt4yf3L
1qnNYKGC7mlbs/uuwc4lAAAADHBlZGVyQGVmc3EtMQE=
-----END OPENSSH PRIVATE KEY-----');
